# PA8, Jonathan Penaloza, V1, Spring 2023

## A

In [1]:
import numpy as np
l1 = [10,20,30,40]
x1 = np.array(l1)
x1.resize(2,2)
x1

array([[10, 20],
       [30, 40]])

In [4]:
x2 = np.square(x1)
x2

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [6]:
x3 = np.add(x2,100)
x3

array([[ 200,  500],
       [1000, 1700]], dtype=int32)

In [8]:
x4 = np.multiply(x3,5)
x4

array([[1000, 2500],
       [5000, 8500]], dtype=int32)

In [9]:
x5 = np.sqrt(x4)
x5

array([[31.6227766 , 50.        ],
       [70.71067812, 92.19544457]])

## B

In [34]:
x6= np.arange(3,28,3)
x6.resize(3,3)
print(x6)
x7= np.arange(10,21,1)
x7.resize(3,3)
print("\n",x7)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [35]:
x8=np.multiply(x6,x7)
print(x8)

[[ 30  66 108]
 [156 210 270]
 [336 408 486]]


## C

In [43]:
x9=np.load('process1.npy')
x10=np.load('process2.npy')
x11=np.load('process3.npy')
x12=np.load('process4.npy')
x13=np.load('process5.npy')

In [44]:
array1=np.vstack([x9,x10,x11,x12,x13])

In [45]:
print(array1)
a,b,c,d,e=np.hsplit(array1,5)
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())
print(e.mean())

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]
72.0
27.8
45.6
12.0
47.8
